<a href="https://colab.research.google.com/github/Chandrika-Saha/Machine-Learning-Algos/blob/main/PandasPokemon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import pandas as pd

In [51]:
df = pd.read_csv("pokemon_data.csv")

In [52]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [53]:
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [54]:
df.tail(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [55]:
print(df.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [56]:
df['Name']

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [57]:
df['Name'][0:5]

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [58]:
df[['Name', 'HP', 'Attack']]

                      Name  HP  Attack
0                Bulbasaur  45      49
1                  Ivysaur  60      62
2                 Venusaur  80      82
3    VenusaurMega Venusaur  80     100
4               Charmander  39      52
..                     ...  ..     ...
795                Diancie  50     100
796    DiancieMega Diancie  50     160
797    HoopaHoopa Confined  80     110
798     HoopaHoopa Unbound  80     160
799              Volcanion  80     110

[800 rows x 3 columns]

In [59]:
df[['Name', 'HP', 'Attack']][0:5]

                    Name  HP  Attack
0              Bulbasaur  45      49
1                Ivysaur  60      62
2               Venusaur  80      82
3  VenusaurMega Venusaur  80     100
4             Charmander  39      52

In [60]:
print(df.iloc[0])
print(df.iloc[0:5])
print(df.iloc[0, 3])

#                     1
Name          Bulbasaur
Type 1            Grass
Type 2           Poison
HP                   45
Attack               49
Defense              49
Sp. Atk              65
Sp. Def              65
Speed                45
Generation            1
Legendary         False
Name: 0, dtype: object
   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False
Poison

In [61]:
for i, r in df.iterrows():
  print(i, r)

Streaming output truncated to the last 5000 lines.
Attack            50
Defense          100
Sp. Atk          100
Sp. Def          200
Speed             50
Generation         3
Legendary       True
Name: 415, dtype: object
416 #                   379
Name          Registeel
Type 1            Steel
Type 2              NaN
HP                   80
Attack               75
Defense             150
Sp. Atk              75
Sp. Def             150
Speed                50
Generation            3
Legendary          True
Name: 416, dtype: object
417 #                 380
Name           Latias
Type 1         Dragon
Type 2        Psychic
HP                 80
Attack             80
Defense            90
Sp. Atk           110
Sp. Def           130
Speed             110
Generation          3
Legendary        True
Name: 417, dtype: object
418 #                           380
Name          LatiasMega Latias
Type 1                   Dragon
Type 2                  Psychic
HP                           80
Attack                      100
Defense                     120
Sp. Atk                     140
Sp. Def                     150
Speed                       110
Generation                    3
Legendary                  True
Name: 418, dtype: object
419 #                 381
Name           Latios
Type 1         Dragon
Type 2        Psychic
HP                 80
Attack             90
Defense            80
Sp. Atk           130
Sp. Def           110
Speed             110
Generation          3
Legendary        True
Name: 419, dtype: object
420 #                           381
Name          LatiosMega Latios
Type 1                   Dragon
Type 2                  Psychic
HP                           80
Attack                      130
Defense                     100
Sp. Atk                     160
Sp. Def                     120
Speed                       110
Generation                    3
Legendary                  True
Name: 420, dtype: object
421 #                382
Name          Kyogre
Type 1         Water
Type 2           NaN
HP               100
Attack           100
Defense           90
Sp. Atk          150
Sp. Def          140
Speed             90
Generation         3
Legendary       True
Name: 421, dtype: object
422 #                             382
Name          KyogrePrimal Kyogre
Type 1                      Water
Type 2                        NaN
HP                            100
Attack                        150
Defense                        90
Sp. Atk                       180
Sp. Def                       160
Speed                          90
Generation                      3
Legendary                    True
Name: 422, dtype: object
423 #                 383
Name          Groudon
Type 1         Ground
Type 2            NaN
HP                100
Attack            150
Defense           140
Sp. Atk           100
Sp. Def            90
Speed              90
Generation          3
Legendary        True
Name: 423, dtype: object
424 #                               383
Name          GroudonPrimal Groudon
Type 1                       Ground
Type 2                         Fire
HP                              100
Attack                          180
Defense                         160
Sp. Atk                         150
Sp. Def                          90
Speed                            90
Generation                        3
Legendary                      True
Name: 424, dtype: object
425 #                  384
Name          Rayquaza
Type 1          Dragon
Type 2          Flying
HP                 105
Attack             150
Defense             90
Sp. Atk            150
Sp. Def             90
Speed               95
Generation           3
Legendary         True
Name: 425, dtype: object
426 #                               384
Name          RayquazaMega Rayquaza
Type 1                       Dragon
Type 2                       Flying
HP                              105
Attack                          180
Defense                         100
Sp. Atk                         180
Sp. Def                         100
Speed                           115
Generation                        3
Legendary                      True
Name: 426, dtype: object
427 #                 385
Name          Jirachi
Type 1          Steel
Type 2        Psychic
HP                100
Attack            100
Defense           100
Sp. Atk           100
Sp. Def           100
Speed             100
Generation          3
Legendary        True
Name: 427, dtype: object
428 #                            386
Name          DeoxysNormal Forme
Type 1                   Psychic
Type 2                       NaN
HP                            50
Attack                       150
Defense                       50
Sp. Atk                      150
Sp. Def                       50
Speed                        150
Generation                     3
Legendary                   True
Name: 428, dtype: object
429 #                            386
Name          DeoxysAttack Forme
Type 1                   Psychic
Type 2                       NaN
HP                            50
Attack                       180
Defense                       20
Sp. Atk                      180
Sp. Def                       20
Speed                        150
Generation                     3
Legendary                   True
Name: 429, dtype: object
430 #                             386
Name          DeoxysDefense Forme
Type 1                    Psychic
Type 2                        NaN
HP                             50
Attack                         70
Defense                       160
Sp. Atk                        70
Sp. Def                       160
Speed                          90
Generation                      3
Legendary                    True
Name: 430, dtype: object
431 #                           386
Name          DeoxysSpeed Forme
Type 1                  Psychic
Type 2                      NaN
HP                           50
Attack                       95
Defense                      90
Sp. Atk                      95
Sp. Def                      90
Speed                       180
Generation                    3
Legendary                  True
Name: 431, dtype: object
432 #                 387
Name          Turtwig
Type 1          Grass
Type 2            NaN
HP                 55
Attack             68
Defense            64
Sp. Atk            45
Sp. Def            55
Speed              31
Generation          4
Legendary       False
Name: 432, dtype: object
433 #                388
Name          Grotle
Type 1         Grass
Type 2           NaN
HP                75
Attack            89
Defense           85
Sp. Atk           55
Sp. Def           65
Speed             36
Generation         4
Legendary      False
Name: 433, dtype: object
434 #                  389
Name          Torterra
Type 1           Grass
Type 2          Ground
HP                  95
Attack             109
Defense            105
Sp. Atk             75
Sp. Def             85
Speed               56
Generation           4
Legendary        False
Name: 434, dtype: object
435 #                  390
Name          Chimchar
Type 1            Fire
Type 2             NaN
HP                  44
Attack              58
Defense             44
Sp. Atk             58
Sp. Def             44
Speed               61
Generation           4
Legendary        False
Name: 435, dtype: object
436 #                  391
Name          Monferno
Type 1            Fire
Type 2        Fighting
HP                  64
Attack              78
Defense             52
Sp. Atk             78
Sp. Def             52
Speed               81
Generation           4
Legendary        False
Name: 436, dtype: object
437 #                   392
Name          Infernape
Type 1             Fire
Type 2         Fighting
HP                   76
Attack              104
Defense              71
Sp. Atk             104
Sp. Def              71
Speed               108
Generation            4
Legendary         False
Name: 437, dtype: object
438 #                393
Name          Piplup
Type 1         Water
Type 2           NaN
HP                53
Attack            51
Defense           53
Sp. Atk           61
Sp. Def           56
Speed             40
Generation         4
Legendary      False
Name: 438, dtype: object
439 #                  394
Name          Prinplup
Type 1           Water
Type 2             NaN
HP                  64
Attack              66
Defense             68
Sp. Atk             81
Sp. Def             76
Speed               50
Generation           4
Legendary        False
Name: 439, dtype: object
440 #                  395
Name          Empoleon
Type 1           Water
Type 2           Steel
HP                  84
Attack              86
Defense             88
Sp. Atk            111
Sp. Def            101
Speed               60
Generation           4
Legendary        False
Name: 440, dtype: object
441 #                396
Name          Starly
Type 1        Normal
Type 2        Flying
HP                40
Attack            55
Defense           30
Sp. Atk           30
Sp. Def           30
Speed             60
Generation         4
Legendary      False
Name: 441, dtype: object
442 #                  397
Name          Staravia
Type 1          Normal
Type 2          Flying
HP                  55
Attack              75
Defense             50
Sp. Atk             40
Sp. Def             40
Speed               80
Generation           4
Legendary        False
Name: 442, dtype: object
443 #                   398
Name          Staraptor
Type 1           Normal
Type 2           Flying
HP                   85
Attack              120
Defense              70
Sp. Atk              50
Sp. Def              60
Speed               100
Generation            4
Legendary         False
Name: 443, dtype: object
444 #                399
Name          Bidoof
Type 1        Normal
Type 2           NaN
HP                59
Attack            45
Defense           40
Sp. Atk           35
Sp. Def           40
Speed             31
Generation         4
Legendary      False
Name: 444, dtype: object
445 #                 400
Name          Bibarel
Type 1         Normal
Type 2          Water
HP                 79
Attack             85
Defense            60
Sp. Atk            55
Sp. Def            60
Speed              71
Generation          4
Legendary       False
Name: 445, dtype: object
446 #                   401
Name          Kricketot
Type 1              Bug
Type 2              NaN
HP                   37
Attack               25
Defense              41
Sp. Atk              25
Sp. Def              41
Speed                25
Generation            4
Legendary         False
Name: 446, dtype: object
447 #                    402
Name          Kricketune
Type 1               Bug
Type 2               NaN
HP                    77
Attack                85
Defense               51
Sp. Atk               55
Sp. Def               51
Speed                 65
Generation             4
Legendary          False
Name: 447, dtype: object
448 #                  403
Name             Shinx
Type 1        Electric
Type 2             NaN
HP                  45
Attack              65
Defense             34
Sp. Atk             40
Sp. Def             34
Speed               45
Generation           4
Legendary        False
Name: 448, dtype: object
449 #                  404
Name             Luxio
Type 1        Electric
Type 2             NaN
HP                  60
Attack              85
Defense             49
Sp. Atk             60
Sp. Def             49
Speed               60
Generation           4
Legendary        False
Name: 449, dtype: object
450 #                  405
Name            Luxray
Type 1        Electric
Type 2             NaN
HP                  80
Attack             120
Defense             79
Sp. Atk             95
Sp. Def             79
Speed               70
Generation           4
Legendary        False
Name: 450, dtype: object
451 #                406
Name           Budew
Type 1         Grass
Type 2        Poison
HP                40
Attack            30
Defense           35
Sp. Atk           50
Sp. Def           70
Speed             55
Generation         4
Legendary      False
Name: 451, dtype: object
452 #                  407
Name          Roserade
Type 1           Grass
Type 2          Poison
HP                  60
Attack              70
Defense             65
Sp. Atk            125
Sp. Def            105
Speed               90
Generation           4
Legendary        False
Name: 452, dtype: object
453 #                  408
Name          Cranidos
Type 1            Rock
Type 2             NaN
HP                  67
Attack             125
Defense             40
Sp. Atk             30
Sp. Def             30
Speed               58
Generation           4
Legendary        False
Name: 453, dtype: object
454 #                   409
Name          Rampardos
Type 1             Rock
Type 2              NaN
HP                   97
Attack              165
Defense              60
Sp. Atk              65
Sp. Def              50
Speed                58
Generation            4
Legendary         False
Name: 454, dtype: object
455 #                  410
Name          Shieldon
Type 1            Rock
Type 2           Steel
HP                  30
Attack              42
Defense            118
Sp. Atk             42
Sp. Def             88
Speed               30
Generation           4
Legendary        False
Name: 455, dtype: object
456 #                   411
Name          Bastiodon
Type 1             Rock
Type 2            Steel
HP                   60
Attack               52
Defense             168
Sp. Atk              47
Sp. Def             138
Speed                30
Generation            4
Legendary         False
Name: 456, dtype: object
457 #               412
Name          Burmy
Type 1          Bug
Type 2          NaN
HP               40
Attack           29
Defense          45
Sp. Atk          29
Sp. Def          45
Speed            36
Generation        4
Legendary     False
Name: 457, dtype: object
458 #                             413
Name          WormadamPlant Cloak
Type 1                        Bug
Type 2                      Grass
HP                             60
Attack                         59
Defense                        85
Sp. Atk                        79
Sp. Def                       105
Speed                          36
Generation                      4
Legendary                   False
Name: 458, dtype: object
459 #                             413
Name          WormadamSandy Cloak
Type 1                        Bug
Type 2                     Ground
HP                             60
Attack                         79
Defense                       105
Sp. Atk                        59
Sp. Def                        85
Speed                          36
Generation                      4
Legendary                   False
Name: 459, dtype: object
460 #                             413
Name          WormadamTrash Cloak
Type 1                        Bug
Type 2                      Steel
HP                             60
Attack                         69
Defense                        95
Sp. Atk                        69
Sp. Def                        95
Speed                          36
Generation                      4
Legendary                   False
Name: 460, dtype: object
461 #                414
Name          Mothim
Type 1           Bug
Type 2        Flying
HP                70
Attack            94
Defense           50
Sp. Atk           94
Sp. Def           50
Speed             66
Generation         4
Legendary      False
Name: 461, dtype: object
462 #                415
Name          Combee
Type 1           Bug
Type 2        Flying
HP                30
Attack            30
Defense           42
Sp. Atk           30
Sp. Def           42
Speed             70
Generation         4
Legendary      False
Name: 462, dtype: object
463 #                   416
Name          Vespiquen
Type 1              Bug
Type 2           Flying
HP                   70
Attack               80
Defense             102
Sp. Atk              80
Sp. Def             102
Speed                40
Generation            4
Legendary         False
Name: 463, dtype: object
464 #                   417
Name          Pachirisu
Type 1         Electric
Type 2              NaN
HP                   60
Attack               45
Defense              70
Sp. Atk              45
Sp. Def              90
Speed                95
Generation            4
Legendary         False
Name: 464, dtype: object
465 #                418
Name          Buizel
Type 1         Water
Type 2           NaN
HP                55
Attack            65
Defense           35
Sp. Atk           60
Sp. Def           30
Speed             85
Generation         4
Legendary      False
Name: 465, dtype: object
466 #                  419
Name          Floatzel
Type 1           Water
Type 2             NaN
HP                  85
Attack             105
Defense             55
Sp. Atk             85
Sp. Def             50
Speed              115
Generation           4
Legendary        False
Name: 466, dtype: object
467 #                 420
Name          Cherubi
Type 1          Grass
Type 2            NaN
HP                 45
Attack             35
Defense            45
Sp. Atk            62
Sp. Def            53
Speed              35
Generation          4
Legendary       False
Name: 467, dtype: object
468 #                 421
Name          Cherrim
Type 1          Grass
Type 2            NaN
HP                 70
Attack             60
Defense            70
Sp. Atk            87
Sp. Def            78
Speed              85
Generation          4
Legendary       False
Name: 468, dtype: object
469 #                 422
Name          Shellos
Type 1          Water
Type 2            NaN
HP                 76
Attack             48
Defense            48
Sp. Atk            57
Sp. Def            62
Speed              34
Generation          4
Legendary       False
Name: 469, dtype: object
470 #                   423
Name          Gastrodon
Type 1            Water
Type 2           Ground
HP                  111
Attack               83
Defense              68
Sp. Atk              92
Sp. Def              82
Speed                39
Generation            4
Legendary         False
Name: 470, dtype: object
471 #                 424
Name          Ambipom
Type 1         Normal
Type 2            NaN
HP                 75
Attack            100
Defense            66
Sp. Atk            60
Sp. Def            66
Speed             115
Generation          4
Legendary       False
Name: 471, dtype: object
472 #                  425
Name          Drifloon
Type 1           Ghost
Type 2          Flying
HP                  90
Attack              50
Defense             34
Sp. Atk             60
Sp. Def             44
Speed               70
Generation           4
Legendary        False
Name: 472, dtype: object
473 #                  426
Name          Drifblim
Type 1           Ghost
Type 2          Flying
HP                 150
Attack              80
Defense             44
Sp. Atk             90
Sp. Def             54
Speed               80
Generation           4
Legendary        False
Name: 473, dtype: object
474 #                 427
Name          Buneary
Type 1         Normal
Type 2            NaN
HP                 55
Attack             66
Defense            44
Sp. Atk            44
Sp. Def            56
Speed              85
Generation          4
Legendary       False
Name: 474, dtype: object
475 #                 428
Name          Lopunny
Type 1         Normal
Type 2            NaN
HP                 65
Attack             76
Defense            84
Sp. Atk            54
Sp. Def            96
Speed             105
Generation          4
Legendary       False
Name: 475, dtype: object
476 #                             428
Name          LopunnyMega Lopunny
Type 1                     Normal
Type 2                   Fighting
HP                             65

In [62]:
for i, r in df.iterrows():
  print(i, r['Name'])

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 CharizardMega Charizard X
8 CharizardMega Charizard Y
9 Squirtle
10 Wartortle
11 Blastoise
12 BlastoiseMega Blastoise
13 Caterpie
14 Metapod
15 Butterfree
16 Weedle
17 Kakuna
18 Beedrill
19 BeedrillMega Beedrill
20 Pidgey
21 Pidgeotto
22 Pidgeot
23 PidgeotMega Pidgeot
24 Rattata
25 Raticate
26 Spearow
27 Fearow
28 Ekans
29 Arbok
30 Pikachu
31 Raichu
32 Sandshrew
33 Sandslash
34 Nidoran (Female)
35 Nidorina
36 Nidoqueen
37 Nidoran (Male)
38 Nidorino
39 Nidoking
40 Clefairy
41 Clefable
42 Vulpix
43 Ninetales
44 Jigglypuff
45 Wigglytuff
46 Zubat
47 Golbat
48 Oddish
49 Gloom
50 Vileplume
51 Paras
52 Parasect
53 Venonat
54 Venomoth
55 Diglett
56 Dugtrio
57 Meowth
58 Persian
59 Psyduck
60 Golduck
61 Mankey
62 Primeape
63 Growlithe
64 Arcanine
65 Poliwag
66 Poliwhirl
67 Poliwrath
68 Abra
69 Kadabra
70 Alakazam
71 AlakazamMega Alakazam
72 Machop
73 Machoke
74 Machamp
75 Bellsprout
76 Weepinbell
77 Victreebel
78 Tentacool
79 Tentacruel
80 Geodude
81 Graveler
82 Golem
83 Ponyta
84 Rapidash
85 Slowpoke
86 Slowbro
87 SlowbroMega Slowbro
88 Magnemite
89 Magneton
90 Farfetch'd
91 Doduo
92 Dodrio
93 Seel
94 Dewgong
95 Grimer
96 Muk
97 Shellder
98 Cloyster
99 Gastly
100 Haunter
101 Gengar
102 GengarMega Gengar
103 Onix
104 Drowzee
105 Hypno
106 Krabby
107 Kingler
108 Voltorb
109 Electrode
110 Exeggcute
111 Exeggutor
112 Cubone
113 Marowak
114 Hitmonlee
115 Hitmonchan
116 Lickitung
117 Koffing
118 Weezing
119 Rhyhorn
120 Rhydon
121 Chansey
122 Tangela
123 Kangaskhan
124 KangaskhanMega Kangaskhan
125 Horsea
126 Seadra
127 Goldeen
128 Seaking
129 Staryu
130 Starmie
131 Mr. Mime
132 Scyther
133 Jynx
134 Electabuzz
135 Magmar
136 Pinsir
137 PinsirMega Pinsir
138 Tauros
139 Magikarp
140 Gyarados
141 GyaradosMega Gyarados
142 Lapras
143 Ditto
144 Eevee
145 Vaporeon
146 Jolteon
147 Flareon
148 Porygon
149 Omanyte
150 Omastar
151 Kabuto
152 Kabutops
153 Aerodactyl
154 AerodactylMega Aerodactyl
155 Snorlax
156 Articuno
157 Zapdos
158 Moltres
159 Dratini
160 Dragonair
161 Dragonite
162 Mewtwo
163 MewtwoMega Mewtwo X
164 MewtwoMega Mewtwo Y
165 Mew
166 Chikorita
167 Bayleef
168 Meganium
169 Cyndaquil
170 Quilava
171 Typhlosion
172 Totodile
173 Croconaw
174 Feraligatr
175 Sentret
176 Furret
177 Hoothoot
178 Noctowl
179 Ledyba
180 Ledian
181 Spinarak
182 Ariados
183 Crobat
184 Chinchou
185 Lanturn
186 Pichu
187 Cleffa
188 Igglybuff
189 Togepi
190 Togetic
191 Natu
192 Xatu
193 Mareep
194 Flaaffy
195 Ampharos
196 AmpharosMega Ampharos
197 Bellossom
198 Marill
199 Azumarill
200 Sudowoodo
201 Politoed
202 Hoppip
203 Skiploom
204 Jumpluff
205 Aipom
206 Sunkern
207 Sunflora
208 Yanma
209 Wooper
210 Quagsire
211 Espeon
212 Umbreon
213 Murkrow
214 Slowking
215 Misdreavus
216 Unown
217 Wobbuffet
218 Girafarig
219 Pineco
220 Forretress
221 Dunsparce
222 Gligar
223 Steelix
224 SteelixMega Steelix
225 Snubbull
226 Granbull
227 Qwilfish
228 Scizor
229 ScizorMega Scizor
230 Shuckle
231 Heracross
232 HeracrossMega Heracross
233 Sneasel
234 Teddiursa
235 Ursaring
236 Slugma
237 Magcargo
238 Swinub
239 Piloswine
240 Corsola
241 Remoraid
242 Octillery
243 Delibird
244 Mantine
245 Skarmory
246 Houndour
247 Houndoom
248 HoundoomMega Houndoom
249 Kingdra
250 Phanpy
251 Donphan
252 Porygon2
253 Stantler
254 Smeargle
255 Tyrogue
256 Hitmontop
257 Smoochum
258 Elekid
259 Magby
260 Miltank
261 Blissey
262 Raikou
263 Entei
264 Suicune
265 Larvitar
266 Pupitar
267 Tyranitar
268 TyranitarMega Tyranitar
269 Lugia
270 Ho-oh
271 Celebi
272 Treecko
273 Grovyle
274 Sceptile
275 SceptileMega Sceptile
276 Torchic
277 Combusken
278 Blaziken
279 BlazikenMega Blaziken
280 Mudkip
281 Marshtomp
282 Swampert
283 SwampertMega Swampert
284 Poochyena
285 Mightyena
286 Zigzagoon
287 Linoone
288 Wurmple
289 Silcoon
290 Beautifly
291 Cascoon
292 Dustox
293 Lotad
294 Lombre
295 Ludicolo
296 Seedot
297 Nuzleaf
298 Shiftry
299 Taillow
300 Swellow
301 Wingull
302 Pelipper
303 Ralts
304 Kirlia
305 Gardevoir
306 GardevoirMega Gardevoir
307 Surskit
308 Masquerain
309 Shroomish
310 Breloom
311 Slakoth
312 Vigoroth
313 Slaking
314 Nincada
315 Ninjask
316 Shedinja
317 Whismur
318 Loudred
319 Exploud
320 Makuhita
321 Hariyama
322 Azurill
323 Nosepass
324 Skitty
325 Delcatty
326 Sableye
327 SableyeMega Sableye
328 Mawile
329 MawileMega Mawile
330 Aron
331 Lairon
332 Aggron
333 AggronMega Aggron
334 Meditite
335 Medicham
336 MedichamMega Medicham
337 Electrike
338 Manectric
339 ManectricMega Manectric
340 Plusle
341 Minun
342 Volbeat
343 Illumise
344 Roselia
345 Gulpin
346 Swalot
347 Carvanha
348 Sharpedo
349 SharpedoMega Sharpedo
350 Wailmer
351 Wailord
352 Numel
353 Camerupt
354 CameruptMega Camerupt
355 Torkoal
356 Spoink
357 Grumpig
358 Spinda
359 Trapinch
360 Vibrava
361 Flygon
362 Cacnea
363 Cacturne
364 Swablu
365 Altaria
366 AltariaMega Altaria
367 Zangoose
368 Seviper
369 Lunatone
370 Solrock
371 Barboach
372 Whiscash
373 Corphish
374 Crawdaunt
375 Baltoy
376 Claydol
377 Lileep
378 Cradily
379 Anorith
380 Armaldo
381 Feebas
382 Milotic
383 Castform
384 Kecleon
385 Shuppet
386 Banette
387 BanetteMega Banette
388 Duskull
389 Dusclops
390 Tropius
391 Chimecho
392 Absol
393 AbsolMega Absol
394 Wynaut
395 Snorunt
396 Glalie
397 GlalieMega Glalie
398 Spheal
399 Sealeo
400 Walrein
401 Clamperl
402 Huntail
403 Gorebyss
404 Relicanth
405 Luvdisc
406 Bagon
407 Shelgon
408 Salamence
409 SalamenceMega Salamence
410 Beldum
411 Metang
412 Metagross
413 MetagrossMega Metagross
414 Regirock
415 Regice
416 Registeel
417 Latias
418 LatiasMega Latias
419 Latios
420 LatiosMega Latios
421 Kyogre
422 KyogrePrimal Kyogre
423 Groudon
424 GroudonPrimal Groudon
425 Rayquaza
426 RayquazaMega Rayquaza
427 Jirachi
428 DeoxysNormal Forme
429 DeoxysAttack Forme
430 DeoxysDefense Forme
431 DeoxysSpeed Forme
432 Turtwig
433 Grotle
434 Torterra
435 Chimchar
436 Monferno
437 Infernape
438 Piplup
439 Prinplup
440 Empoleon
441 Starly
442 Staravia
443 Staraptor
444 Bidoof
445 Bibarel
446 Kricketot
447 Kricketune
448 Shinx
449 Luxio
450 Luxray
451 Budew
452 Roserade
453 Cranidos
454 Rampardos
455 Shieldon
456 Bastiodon
457 Burmy
458 WormadamPlant Cloak
459 WormadamSandy Cloak
460 WormadamTrash Cloak
461 Mothim
462 Combee
463 Vespiquen
464 Pachirisu
465 Buizel
466 Floatzel
467 Cherubi
468 Cherrim
469 Shellos
470 Gastrodon
471 Ambipom
472 Drifloon
473 Drifblim
474 Buneary
475 Lopunny
476 LopunnyMega Lopunny
477 Mismagius
478 Honchkrow
479 Glameow
480 Purugly
481 Chingling
482 Stunky
483 Skuntank
484 Bronzor
485 Bronzong
486 Bonsly
487 Mime Jr.
488 Happiny
489 Chatot
490 Spiritomb
491 Gible
492 Gabite
493 Garchomp
494 GarchompMega Garchomp
495 Munchlax
496 Riolu
497 Lucario
498 LucarioMega Lucario
499 Hippopotas
500 Hippowdon
501 Skorupi
502 Drapion
503 Croagunk
504 Toxicroak
505 Carnivine
506 Finneon
507 Lumineon
508 Mantyke
509 Snover
510 Abomasnow
511 AbomasnowMega Abomasnow
512 Weavile
513 Magnezone
514 Lickilicky
515 Rhyperior
516 Tangrowth
517 Electivire
518 Magmortar
519 Togekiss
520 Yanmega
521 Leafeon
522 Glaceon
523 Gliscor
524 Mamoswine
525 Porygon-Z
526 Gallade
527 GalladeMega Gallade
528 Probopass
529 Dusknoir
530 Froslass
531 Rotom
532 RotomHeat Rotom
533 RotomWash Rotom
534 RotomFrost Rotom
535 RotomFan Rotom
536 RotomMow Rotom
537 Uxie
538 Mesprit
539 Azelf
540 Dialga
541 Palkia
542 Heatran
543 Regigigas
544 GiratinaAltered Forme
545 GiratinaOrigin Forme
546 Cresselia
547 Phione
548 Manaphy
549 Darkrai
550 ShayminLand Forme
551 ShayminSky Forme
552 Arceus
553 Victini
554 Snivy
555 Servine
556 Serperior
557 Tepig
558 Pignite
559 Emboar
560 Oshawott
561 Dewott
562 Samurott
563 Patrat
564 Watchog
565 Lillipup
566 Herdier
567 Stoutland
568 Purrloin
569 Liepard
570 Pansage
571 Simisage
572 Pansear
573 Simisear
574 Panpour
575 Simipour
576 Munna
577 Musharna
578 Pidove
579 Tranquill
580 Unfezant
581 Blitzle
582 Zebstrika
583 Roggenrola
584 Boldore
585 Gigalith
586 Woobat
587 Swoobat
588 Drilbur
589 Excadrill
590 Audino
591 AudinoMega Audino
592 Timburr
593 Gurdurr
594 Conkeldurr
595 Tympole
596 Palpitoad
597 Seismitoad
598 Throh
599 Sawk
600 Sewaddle
601 Swadloon
602 Leavanny
603 Venipede
604 Whirlipede
605 Scolipede
606 Cottonee
607 Whimsicott
608 Petilil
609 Lilligant
610 Basculin
611 Sandile
612 Krokorok
613 Krookodile
614 Darumaka
615 DarmanitanStandard Mode
616 DarmanitanZen Mode
617 Maractus
618 Dwebble
619 Crustle
620 Scraggy
621 Scrafty
622 Sigilyph
623 Yamask
624 Cofagrigus
625 Tirtouga
626 Carracosta
627 Archen
628 Archeops
629 Trubbish
630 Garbodor
631 Zorua
632 Zoroark
633 Minccino
634 Cinccino
635 Gothita
636 Gothorita
637 Gothitelle
638 Solosis
639 Duosion
640 Reuniclus
641 Ducklett
642 Swanna
643 Vanillite
644 Vanillish
645 Vanilluxe
646 Deerling
647 Sawsbuck
648 Emolga
649 Karrablast
650 Escavalier
651 Foongus
652 Amoonguss
653 Frillish
654 Jellicent
655 Alomomola
656 Joltik
657 Galvantula
658 Ferroseed
659 Ferrothorn
660 Klink
661 Klang
662 Klinklang
663 Tynamo
664 Eelektrik
665 Eelektross
666 Elgyem
667 Beheeyem
668 Litwick
669 Lampent
670 Chandelure
671 Axew
672 Fraxure
673 Haxorus
674 Cubchoo
675 Beartic
676 Cryogonal
677 Shelmet
678 Accelgor
679 Stunfisk
680 Mienfoo
681 Mienshao
682 Druddigon
683 Golett
684 Golurk
685 Pawniard
686 Bisharp
687 Bouffalant
688 Rufflet
689 Braviary
690 Vullaby
691 Mandibuzz
692 Heatmor
693 Durant
694 Deino
695 Zweilous
696 Hydreigon
697 Larvesta
698 Volcarona
699 Cobalion
700 Terrakion
701 Virizion
702 TornadusIncarnate Forme
703 TornadusTherian Forme
704 ThundurusIncarnate Forme
705 ThundurusTherian Forme
706 Reshiram
707 Zekrom
708 LandorusIncarnate Forme
709 LandorusTherian Forme
710 Kyurem
711 KyuremBlack Kyurem
712 KyuremWhite Kyurem
713 KeldeoOrdinary Forme
714 KeldeoResolute Forme
715 MeloettaAria Forme
716 MeloettaPirouette Forme
717 Genesect
718 Chespin
719 Quilladin
720 Chesnaught
721 Fennekin
722 Braixen
723 Delphox
724 Froakie
725 Frogadier
726 Greninja
727 Bunnelby
728 Diggersby
729 Fletchling
730 Fletchinder
731 Talonflame
732 Scatterbug
733 Spewpa
734 Vivillon
735 Litleo
736 Pyroar
737 Flabébé
738 Floette
739 Florges
740 Skiddo
741 Gogoat
742 Pancham
743 Pangoro
744 Furfrou
745 Espurr
746 MeowsticMale
747 MeowsticFemale
748 Honedge
749 Doublade
750 AegislashBlade Forme
751 AegislashShield Forme
752 Spritzee
753 Aromatisse
754 Swirlix
755 Slurpuff
756 Inkay
757 Malamar
758 Binacle
759 Barbaracle
760 Skrelp
761 Dragalge
762 Clauncher
763 Clawitzer
764 Helioptile
765 Heliolisk
766 Tyrunt
767 Tyrantrum
768 Amaura
769 Aurorus
770 Sylveon
771 Hawlucha
772 Dedenne
773 Carbink
774 Goomy
775 Sliggoo
776 Goodra
777 Klefki
778 Phantump
779 Trevenant
780 PumpkabooAverage Size
781 PumpkabooSmall Size
782 PumpkabooLarge Size
783 PumpkabooSuper Size
784 GourgeistAverage Size
785 GourgeistSmall Size
786 GourgeistLarge Size
787 GourgeistSuper Size
788 Bergmite
789 Avalugg
790 Noibat
791 Noivern
792 Xerneas
793 Yveltal
794 Zygarde50% Forme
795 Diancie
796 DiancieMega Diancie
797 HoopaHoopa Confined
798 HoopaHoopa Unbound
799 Volcanion

In [63]:
df.loc[df['Defense']>150]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
87,80,SlowbroMega Slowbro,Water,Psychic,95,75,180,130,80,30,1,False
98,91,Cloyster,Water,Ice,50,95,180,85,45,70,1,False
103,95,Onix,Rock,Ground,35,45,160,30,45,70,1,False
223,208,Steelix,Steel,Ground,75,85,200,55,65,30,2,False
224,208,SteelixMega Steelix,Steel,Ground,75,125,230,55,95,30,2,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
332,306,Aggron,Steel,Rock,70,110,180,60,60,50,3,False
333,306,AggronMega Aggron,Steel,NaN,70,140,230,60,80,50,3,False
414,377,Regirock,Rock,NaN,80,100,200,50,100,50,3,True
424,383,GroudonPrimal Groudon,Ground,Fire,100,180,160,150,90,90,3,True
430,386,DeoxysDefense Forme,Psychic,NaN,50,70,160,70,160,90,3,True
456,411,Bastiodon,Rock,Steel,60,52,168,47,138,30,4,False
789,713,Avalugg,Ice,NaN,95,117,184,44,46,28,6,False

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 69.7+ KB

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 69.7+ KB

In [66]:
df.describe().T

            count       mean         std   min     25%    50%     75%    max
#           800.0  362.81375  208.343798   1.0  184.75  364.5  539.25  721.0
HP          800.0   69.25875   25.534669   1.0   50.00   65.0   80.00  255.0
Attack      800.0   79.00125   32.457366   5.0   55.00   75.0  100.00  190.0
Defense     800.0   73.84250   31.183501   5.0   50.00   70.0   90.00  230.0
Sp. Atk     800.0   72.82000   32.722294  10.0   49.75   65.0   95.00  194.0
Sp. Def     800.0   71.90250   27.828916  20.0   50.00   70.0   90.00  230.0
Speed       800.0   68.27750   29.060474   5.0   45.00   65.0   90.00  180.0
Generation  800.0    3.32375    1.661290   1.0    2.00    3.0    5.00    6.0

In [67]:
df.sort_values('Name')

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [68]:
df.sort_values('Name', ascending=False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False

In [69]:
df.sort_values(['Name', 'Type 1'])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [70]:
df.sort_values(['Name', 'Type 1'], ascending=[True, False])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [71]:
df['Total'] = df['Attack'] + df['Defense']

In [72]:
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,98
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,125
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,165
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,223
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,95

In [73]:
df.drop(columns=['Total'], inplace=True)
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [74]:
df['Total'] = df.iloc[:, 4:6].sum(axis=1)
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,94
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,122
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,162
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,180
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,91

In [75]:
columns = list(df.columns.values)
print(columns)
df = df[columns[0:4] + [columns[-1]] + columns[4:12]]
df.head(5)

['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Total']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,94,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,122,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,162,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,180,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,91,39,52,43,60,50,65,1,False

In [76]:
df.to_csv('chandged.csv')

In [77]:
df.to_csv('changed2.csv', index=False)

# Filtering data

In [78]:
df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP'] > 70)].reset_index(drop=True)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,3,Venusaur,Grass,Poison,162,80,82,83,100,100,80,1,False
1,3,VenusaurMega Venusaur,Grass,Poison,180,80,100,123,122,120,80,1,False
2,45,Vileplume,Grass,Poison,155,75,80,85,110,90,50,1,False
3,71,Victreebel,Grass,Poison,185,80,105,65,100,70,70,1,False
4,591,Amoonguss,Grass,Poison,199,114,85,70,85,80,30,5,False

In [79]:
df.loc[df['Name'].str.contains("Mega")]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,180,80,100,123,122,120,80,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,208,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,182,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,182,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,215,65,150,40,15,80,145,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,163,83,80,80,135,80,121,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,105,55,50,65,175,95,150,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,170,95,75,180,130,80,30,1,False
102,94,GengarMega Gengar,Ghost,Poison,125,60,65,80,170,95,130,1,False
124,115,KangaskhanMega Kangaskhan,Normal,NaN,230,105,125,100,60,100,100,1,False
137,127,PinsirMega Pinsir,Bug,Flying,220,65,155,120,65,90,105,1,False
141,130,GyaradosMega Gyarados,Water,Dark,250,95,155,109,70,130,81,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,215,80,135,85,70,95,150,1,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,296,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,256,106,150,70,194,120,140,1,True
168,154,Meganium,Grass,NaN,162,80,82,100,83,100,80,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,185,90,95,105,165,110,45,2,False
224,208,SteelixMega Steelix,Steel,Ground,200,75,125,230,55,95,30,2,False
229,212,ScizorMega Scizor,Bug,Steel,220,70,150,140,65,100,75,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,265,80,185,115,40,105,75,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,165,75,90,90,140,90,115,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,264,100,164,150,95,120,71,2,False
275,254,SceptileMega Sceptile,Grass,Dragon,180,70,110,75,145,85,145,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,240,80,160,80,130,80,100,3,False
283,260,SwampertMega Swampert,Water,Ground,250,100,150,110,95,110,70,3,False
306,282,GardevoirMega Gardevoir,Psychic,Fairy,153,68,85,65,165,135,100,3,False
327,302,SableyeMega Sableye,Dark,Ghost,135,50,85,125,85,115,20,3,False
329,303,MawileMega Mawile,Steel,Fairy,155,50,105,125,55,95,50,3,False
333,306,AggronMega Aggron,Steel,NaN,210,70,140,230,60,80,50,3,False
336,308,MedichamMega Medicham,Fighting,Psychic,160,60,100,85,80,85,100,3,False
339,310,ManectricMega Manectric,Electric,NaN,145,70,75,80,135,80,135,3,False
349,319,SharpedoMega Sharpedo,Water,Dark,210,70,140,70,110,65,105,3,False
354,323,CameruptMega Camerupt,Fire,Ground,190,70,120,100,145,105,20,3,False
366,334,AltariaMega Altaria,Dragon,Fairy,185,75,110,110,110,105,80,3,False
387,354,BanetteMega Banette,Ghost,NaN,229,64,165,75,93,83,75,3,False
393,359,AbsolMega Absol,Dark,NaN,215,65,150,60,115,60,115,3,False
397,362,GlalieMega Glalie,Ice,NaN,200,80,120,80,120,80,100,3,False
409,373,SalamenceMega Salamence,Dragon,Flying,240,95,145,130,120,90,120,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,225,80,145,150,105,110,110,3,False
418,380,LatiasMega Latias,Dragon,Psychic,180,80,100,120,140,150,110,3,True
420,381,LatiosMega Latios,Dragon,Psychic,210,80,130,100,160,120,110,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,285,105,180,100,180,100,115,3,True
476,428,LopunnyMega Lopunny,Normal,Fighting,201,65,136,94,54,96,135,4,False
494,445,GarchompMega Garchomp,Dragon,Ground,278,108,170,115,120,95,92,4,False
498,448,LucarioMega Lucario,Fighting,Steel,215,70,145,88,140,70,112,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,222,90,132,105,132,105,30,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,233,68,165,95,65,115,110,4,False
591,531,AudinoMega Audino,Normal,Fairy,163,103,60,126,80,126,50,5,False
796,719,DiancieMega Diancie,Rock,Fairy,210,50,160,110,160,110,110,6,True

In [80]:
df.loc[~df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,94,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,122,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,162,80,82,83,100,100,80,1,False
4,4,Charmander,Fire,NaN,91,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,122,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,208,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,150,50,100,150,100,150,50,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,190,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,240,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,190,80,110,120,130,90,70,6,True

In [81]:
import re

df.loc[df['Type 1'].str.contains('fire|grass', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,94,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,122,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,162,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,180,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,91,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,112,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,154,86,68,72,109,66,106,6,False
740,672,Skiddo,Grass,NaN,131,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,223,123,100,62,97,81,68,6,False
799,721,Volcanion,Fire,Water,190,80,110,120,130,90,70,6,True

In [82]:
df.loc[df['Name'].str.contains('^pidg[a-z]*', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,85,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,123,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,163,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,163,83,80,80,135,80,121,1,False

In [83]:
df.loc[df['Name'].str.contains('^pidg[a-z]$', flags=re.I, regex=True)]

Empty DataFrame
Columns: [#, Name, Type 1, Type 2, Total, HP, Attack, Defense, Sp. Atk, Sp. Def, Speed, Generation, Legendary]
Index: []

In [84]:
df.loc[df['Name'].str.contains('^pidg[a-z]{2}$', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,85,40,45,40,35,35,56,1,False

In [85]:
df.loc[df['Name'].str.contains('[a-z]*ing$', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
39,34,Nidoking,Poison,Ground,183,81,102,77,85,75,85,1,False
117,109,Koffing,Poison,NaN,105,40,65,95,60,45,35,1,False
118,110,Weezing,Poison,NaN,155,65,90,120,85,70,60,1,False
128,119,Seaking,Water,NaN,172,80,92,65,65,80,68,1,False
214,199,Slowking,Water,Psychic,170,95,75,80,100,110,30,2,False
235,217,Ursaring,Normal,NaN,220,90,130,75,75,75,55,2,False
313,289,Slaking,Normal,NaN,310,150,160,100,95,65,100,3,False
481,433,Chingling,Psychic,NaN,75,45,30,50,65,50,45,4,False
646,585,Deerling,Normal,Grass,120,60,60,50,40,50,75,5,False
729,661,Fletchling,Normal,Flying,95,45,50,43,40,38,62,6,False

In [86]:
df.loc[df['Type 1'] == 'Fire', 'Type 1'] = 'Flamer'

In [87]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,94,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,122,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,162,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,180,80,100,123,122,120,80,1,False
4,4,Charmander,Flamer,NaN,91,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,150,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,210,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,190,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,240,80,160,60,170,130,80,6,True
799,721,Volcanion,Flamer,Water,190,80,110,120,130,90,70,6,True

In [88]:
df.loc[df['Type 1'] == 'Flamer', 'Type 1'] = 'Fire'

In [89]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,94,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,122,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,162,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,180,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,91,39,52,43,60,50,65,1,False

In [90]:
df.loc[df['Type 1'] == 'Fire', 'Legendary'] = True
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,94,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,122,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,162,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,180,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,91,39,52,43,60,50,65,1,True

In [91]:
df.loc[df['HP'] > 40, ['Generation', 'Legendary']] = ['Test 1', 'Test 2']

/tmp/ipython-input-1445532974.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Test 1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['HP'] > 40, ['Generation', 'Legendary']] = ['Test 1', 'Test 2']
/tmp/ipython-input-1445532974.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Test 2' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df.loc[df['HP'] > 40, ['Generation', 'Legendary']] = ['Test 1', 'Test 2']

In [92]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,94,45,49,49,65,65,45,Test 1,Test 2
1,2,Ivysaur,Grass,Poison,122,60,62,63,80,80,60,Test 1,Test 2
2,3,Venusaur,Grass,Poison,162,80,82,83,100,100,80,Test 1,Test 2
3,3,VenusaurMega Venusaur,Grass,Poison,180,80,100,123,122,120,80,Test 1,Test 2
4,4,Charmander,Fire,NaN,91,39,52,43,60,50,65,1,True

In [94]:
df.groupby(['Type 2']).mean(numeric_only=True).sort_values('HP', ascending=True)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
Type 2,,,,,,,,
Bug,382.000000,143.333333,53.333333,90.000000,80.000000,46.666667,61.666667,61.666667
Poison,169.970588,126.352941,58.764706,67.588235,59.558824,74.029412,69.911765,66.647059
Ghost,551.714286,143.285714,59.142857,84.142857,82.285714,73.214286,78.071429,53.857143
Grass,505.400000,136.800000,62.640000,74.160000,80.120000,60.160000,74.520000,57.320000
Water,400.000000,132.857143,62.714286,70.142857,85.071429,74.500000,68.642857,57.142857
Normal,681.000000,116.250000,63.500000,52.750000,53.750000,88.000000,64.250000,89.250000
Fairy,379.043478,125.913043,64.304348,61.608696,73.869565,75.000000,81.956522,61.217391
Steel,435.636364,157.227273,64.636364,92.590909,104.636364,77.727273,86.272727,59.363636
Rock,347.785714,152.071429,68.071429,84.000000,126.857143,51.142857,68.571429,36.000000
Fire,481.833333,152.500000,71.250000,81.250000,80.166667,110.416667,83.500000,79.666667
Flying,331.103093,151.680412,71.391753,80.288660,68.309278,75.628866,71.206186,85.721649
Psychic,337.151515,146.909091,72.212121,74.696970,87.030303,88.030303,87.606061,69.484848
Dark,413.850000,185.350000,75.550000,109.800000,72.050000,81.800000,69.850000,75.350000
Ground,307.600000,167.085714,77.228571,89.857143,90.314286,65.542857,66.742857,54.657143
Fighting,438.192308,192.307692,79.461538,112.846154,82.500000,81.269231,82.384615,87.384615
Dragon,482.555556,176.611111,82.166667,94.444444,87.055556,98.500000,83.444444,80.555556
Electric,465.666667,160.833333,88.166667,72.666667,68.333333,81.166667,73.500000,71.500000
Ice,441.285714,188.000000,90.000000,98.000000,85.642857,92.642857,84.785714,74.642857

In [101]:
print(sorted(df['Type 1'].unique()))

['Bug', 'Dark', 'Dragon', 'Electric', 'Fairy', 'Fighting', 'Fire', 'Flying', 'Ghost', 'Grass', 'Ground', 'Ice', 'Normal', 'Poison', 'Psychic', 'Rock', 'Steel', 'Water']

In [102]:
print(len(sorted(df['Type 1'].dropna().unique())))

18

In [104]:
df['Types'] = df['Type 1'] + "&" + df['Type 2']
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Types
0,1,Bulbasaur,Grass,Poison,94,45,49,49,65,65,45,Test 1,Test 2,Grass&Poison
1,2,Ivysaur,Grass,Poison,122,60,62,63,80,80,60,Test 1,Test 2,Grass&Poison
2,3,Venusaur,Grass,Poison,162,80,82,83,100,100,80,Test 1,Test 2,Grass&Poison
3,3,VenusaurMega Venusaur,Grass,Poison,180,80,100,123,122,120,80,Test 1,Test 2,Grass&Poison
4,4,Charmander,Fire,NaN,91,39,52,43,60,50,65,1,True,NaN

In [105]:
df.groupby(['Types']).sum(numeric_only=True)

                  #  Total   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
Types
Bug&Electric   1191    244  120     124      110      154      110    173
Bug&Fighting    428    470  160     310      190       80      200    160
Bug&Fire       1273    285  140     145      120      185      160    160
Bug&Flying     4008   1864  882     982      862     1020      967   1160
Bug&Ghost       292     91    1      90       45       30       30     40
...             ...    ...  ...     ...      ...      ...      ...    ...
Water&Ice       309    520  270     250      340      240      235    200
Water&Poison    356    390  185     205      175      185      275    255
Water&Psychic   559    800  435     365      520      470      395    220
Water&Rock     1720    614  283     331      451      246      260    144
Water&Steel     395    170   84      86       88      111      101     60

[136 rows x 8 columns]

In [109]:
df['count'] = 1
df.groupby('Type 1').sum(numeric_only=True)['count']

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: count, dtype: int64

In [110]:
df.groupby(['Type 1', 'Type 2']).sum(numeric_only=True)

                    #  Total   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
Type 1 Type 2
Bug    Electric  1191    244  120     124      110      154      110    173
       Fighting   428    470  160     310      190       80      200    160
       Fire      1273    285  140     145      120      185      160    160
       Flying    4008   1864  882     982      862     1020      967   1160
       Ghost      292     91    1      90       45       30       30     40
...               ...    ...  ...     ...      ...      ...      ...    ...
Water  Ice        309    520  270     250      340      240      235    200
       Poison     356    390  185     205      175      185      275    255
       Psychic    559    800  435     365      520      470      395    220
       Rock      1720    614  283     331      451      246      260    144
       Steel      395    170   84      86       88      111      101     60

                 count
Type 1 Type 2
Bug    Electric      2
       Fighting      2
       Fire          2
       Flying       14
       Ghost         1
...                ...
Water  Ice           3
       Poison        3
       Psychic       5
       Rock          4
       Steel         1

[136 rows x 9 columns]

In [111]:
df.groupby('Type 1')['HP'].median()

Type 1
Bug         60.0
Dark        65.0
Dragon      80.0
Electric    60.0
Fairy       78.0
Fighting    70.0
Fire        70.0
Flying      79.0
Ghost       59.5
Grass       65.5
Ground      75.0
Ice         70.0
Normal      70.0
Poison      67.5
Psychic     68.0
Rock        68.5
Steel       60.0
Water       70.0
Name: HP, dtype: float64

In [112]:
import numpy as np
df.groupby('Type 1')['HP'].aggregate(['min', np.median, np.std])

/tmp/ipython-input-192562578.py:2: FutureWarning: The provided callable <function median at 0x7994fff29b20> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby('Type 1')['HP'].aggregate(['min', np.median, np.std])
/tmp/ipython-input-192562578.py:2: FutureWarning: The provided callable <function std at 0x7995031f9bc0> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  df.groupby('Type 1')['HP'].aggregate(['min', np.median, np.std])

          min  median        std
Type 1
Bug         1    60.0  16.328914
Dark       35    65.0  21.078297
Dragon     41    80.0  23.795415
Electric   20    60.0  17.306511
Fairy      35    78.0  23.587291
Fighting   30    70.0  25.852695
Fire       38    70.0  19.404123
Flying     40    79.0  20.694202
Ghost      20    59.5  31.685895
Grass      30    65.5  19.516564
Ground     10    75.0  25.662492
Ice        36    70.0  21.286861
Normal     30    70.0  36.233430
Poison     35    67.5  19.665019
Psychic    20    68.0  28.421340
Rock       30    68.5  20.833884
Steel      40    60.0  16.044010
Water      20    70.0  27.487026

In [113]:
df.groupby('Types').aggregate({'HP': 'min', 'Attack':'max', 'Defense': 'median'})

               HP  Attack  Defense
Types
Bug&Electric   50      77     55.0
Bug&Fighting   80     185     95.0
Bug&Fire       55      85     60.0
Bug&Flying     30     155     50.0
Bug&Ghost       1      90     45.0
...            ..     ...      ...
Water&Ice      50      95     80.0
Water&Poison   40      95     65.0
Water&Psychic  60      75     85.0
Water&Rock     54     108    116.5
Water&Steel    84      86     88.0

[136 rows x 3 columns]

In [114]:
df.groupby('Type 1')[['HP', 'Attack', 'Defense']].std()

                 HP     Attack    Defense
Type 1
Bug       16.328914  37.040904  33.617609
Dark      21.078297  25.774247  25.121982
Dragon    23.795415  33.742622  24.102938
Electric  17.306511  23.764169  24.757033
Fairy     23.587291  29.751298  18.979478
Fighting  25.852695  28.290163  18.578163
Fire      19.404123  28.769275  23.658200
Flying    20.694202  37.500000  21.360009
Ghost     31.685895  29.629687  32.551138
Grass     19.516564  25.380520  24.485192
Ground    25.662492  33.059087  33.786912
Ice       21.286861  27.289511  34.387708
Normal    36.233430  30.295862  23.771833
Poison    19.665019  19.630010  21.066128
Psychic   28.421340  42.309265  28.359401
Rock      20.833884  35.325458  36.447209
Steel     16.044010  30.388276  44.806548
Water     27.487026  28.377192  27.773809

In [115]:
def filter_func(x):
  return x['HP'].std() > 20

In [118]:
df.groupby('Type 1').filter(filter_func).reset_index(drop=True).set_index('Type 1')

,#,Name,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Types,count
Type 1,,,,,,,,,,,,,,
Water,7,Squirtle,NaN,92,44,48,65,50,64,43,Test 1,Test 2,NaN,1
Water,8,Wartortle,NaN,122,59,63,80,65,80,58,Test 1,Test 2,NaN,1
Water,9,Blastoise,NaN,162,79,83,100,85,105,78,Test 1,Test 2,NaN,1
Water,9,BlastoiseMega Blastoise,NaN,182,79,103,120,135,115,78,Test 1,Test 2,NaN,1
Normal,16,Pidgey,Flying,85,40,45,40,35,35,56,1,False,Normal&Flying,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Dragon,718,Zygarde50% Forme,Ground,208,108,100,121,81,95,95,Test 1,Test 2,Dragon&Ground,1
Rock,719,Diancie,Fairy,150,50,100,150,100,150,50,Test 1,Test 2,Rock&Fairy,1
Rock,719,DiancieMega Diancie,Fairy,210,50,160,110,160,110,110,Test 1,Test 2,Rock&Fairy,1
Psychic,720,HoopaHoopa Confined,Ghost,190,80,110,60,150,130,70,Test 1,Test 2,Psychic&Ghost,1
Psychic,720,HoopaHoopa Unbound,Dark,240,80,160,60,170,130,80,Test 1,Test 2,Psychic&Dark,1

In [125]:
df3 = {
    'key': ['A', 'B', 'C', 'A', 'C'],
    'data1': [0, 1, 2, 3, 4],
    'data2': [5, 6, 7, 8, 9]
}
df3 = pd.DataFrame(df3)
df3

  key  data1  data2
0   A      0      5
1   B      1      6
2   C      2      7
3   A      3      8
4   C      4      9

In [126]:
df3.groupby('key').mean()

     data1  data2
key
A      1.5    6.5
B      1.0    6.0
C      3.0    8.0

In [127]:
def fun(x):
  return x['data1'].mean() >= 2

In [128]:
df3.groupby('key').filter(fun).reset_index(drop=True)

  key  data1  data2
0   C      2      7
1   C      4      9

In [129]:
df.groupby('Type 1')['HP'].transform(lambda x: x-x.mean())

0     -22.271429
1      -7.271429
2      12.728571
3      12.728571
4     -30.903846
         ...
795   -15.363636
796   -15.363636
797     9.368421
798     9.368421
799    10.096154
Name: HP, Length: 800, dtype: float64

In [130]:
def norm_by_data(x):
  x['Attack'] /= x['HP'].sum()
  return x

df.groupby('Type 1')[['HP', 'Attack']].apply(norm_by_data)

            HP    Attack
Type 1
Bug    13   45  0.007643
       14   50  0.005096
       15   60  0.011465
       16   40  0.008917
       17   45  0.006369
...         ..       ...
Water  724  41  0.006938
       725  54  0.007806
       726  72  0.011771
       762  50  0.006567
       763  71  0.009045

[800 rows x 2 columns]

In [134]:
import random
lst = []
for i in range(len(df)):
  lst.append(random.randint(0, 3))

print(lst)
df['lst'] = lst
df.groupby('lst').sum(numeric_only=True)['count']

[2, 2, 3, 3, 1, 3, 1, 3, 0, 2, 1, 0, 2, 3, 3, 1, 0, 3, 2, 0, 2, 3, 0, 2, 0, 2, 2, 3, 0, 1, 3, 0, 1, 1, 3, 1, 1, 1, 2, 1, 3, 1, 0, 2, 0, 2, 2, 2, 3, 3, 0, 0, 2, 2, 2, 0, 0, 2, 3, 3, 2, 1, 3, 1, 2, 1, 1, 3, 1, 0, 1, 0, 3, 1, 2, 1, 1, 3, 2, 2, 3, 3, 0, 3, 2, 0, 2, 0, 3, 2, 3, 2, 0, 2, 3, 0, 1, 0, 0, 2, 1, 2, 1, 0, 3, 3, 1, 2, 3, 3, 0, 3, 2, 3, 0, 0, 2, 2, 3, 3, 3, 1, 1, 0, 3, 2, 1, 0, 2, 3, 3, 1, 2, 1, 0, 1, 3, 3, 1, 1, 3, 2, 0, 0, 3, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 3, 1, 2, 2, 2, 2, 1, 1, 0, 3, 3, 1, 1, 1, 3, 1, 1, 0, 3, 0, 1, 3, 1, 3, 1, 3, 2, 1, 0, 3, 2, 1, 2, 3, 2, 3, 0, 2, 3, 1, 0, 1, 1, 1, 3, 2, 3, 0, 2, 0, 0, 3, 3, 1, 3, 2, 1, 2, 3, 2, 0, 2, 1, 3, 2, 1, 0, 3, 3, 1, 0, 2, 2, 0, 2, 1, 1, 0, 3, 3, 3, 0, 3, 2, 1, 2, 0, 1, 1, 2, 3, 2, 3, 3, 3, 2, 3, 0, 2, 0, 2, 2, 3, 1, 1, 2, 1, 2, 1, 0, 3, 0, 2, 2, 0, 3, 3, 0, 0, 0, 1, 3, 3, 0, 1, 3, 0, 0, 1, 0, 3, 3, 2, 2, 3, 3, 1, 1, 3, 3, 3, 3, 3, 3, 3, 0, 0, 2, 2, 2, 0, 3, 1, 1, 2, 2, 1, 3, 2, 2, 0, 1, 3, 2, 0, 2, 2, 2, 3, 0, 0, 1, 0, 2, 2, 0, 0, 2, 2, 2, 0, 3, 3, 3, 3, 0, 2, 3, 1, 0, 0, 0, 2, 1, 3, 1, 1, 0, 0, 2, 1, 2, 3, 0, 2, 3, 0, 3, 3, 3, 2, 0, 0, 0, 2, 0, 0, 3, 1, 0, 1, 0, 0, 2, 1, 2, 3, 1, 1, 3, 3, 2, 3, 3, 0, 2, 2, 0, 3, 2, 3, 3, 3, 0, 0, 0, 1, 0, 3, 2, 1, 0, 2, 1, 0, 0, 3, 0, 3, 0, 1, 3, 0, 2, 0, 2, 1, 3, 2, 1, 2, 0, 2, 0, 0, 2, 0, 0, 2, 1, 2, 1, 1, 2, 0, 3, 0, 3, 0, 0, 1, 3, 3, 3, 2, 2, 2, 0, 0, 3, 0, 3, 0, 1, 2, 0, 2, 1, 3, 3, 0, 1, 1, 2, 0, 0, 2, 3, 0, 3, 1, 0, 3, 2, 3, 3, 0, 1, 3, 1, 1, 2, 0, 2, 2, 1, 2, 2, 0, 2, 3, 3, 2, 2, 1, 1, 0, 2, 2, 0, 1, 1, 0, 2, 2, 3, 1, 0, 2, 1, 2, 2, 1, 3, 3, 0, 2, 2, 0, 0, 2, 0, 1, 3, 0, 1, 2, 0, 1, 1, 3, 1, 1, 1, 3, 1, 1, 2, 3, 1, 1, 1, 3, 1, 2, 0, 2, 3, 1, 2, 3, 0, 2, 2, 1, 1, 2, 2, 2, 0, 3, 0, 0, 0, 3, 0, 3, 1, 1, 3, 2, 1, 3, 2, 3, 1, 3, 0, 2, 1, 2, 0, 1, 2, 0, 2, 1, 0, 0, 2, 3, 1, 2, 2, 1, 0, 3, 1, 3, 3, 3, 2, 3, 1, 0, 0, 0, 0, 3, 0, 2, 3, 1, 2, 1, 3, 1, 0, 3, 1, 0, 0, 2, 1, 0, 3, 0, 2, 3, 3, 2, 2, 3, 0, 1, 1, 3, 3, 0, 0, 1, 3, 2, 1, 2, 0, 3, 3, 3, 3, 0, 0, 3, 2, 2, 1, 3, 2, 0, 1, 1, 3, 1, 1, 0, 1, 3, 3, 0, 3, 3, 2, 3, 2, 3, 2, 1, 1, 3, 3, 0, 3, 1, 0, 1, 3, 2, 0, 2, 0, 1, 2, 0, 3, 3, 0, 1, 2, 0, 2, 0, 1, 2, 3, 3, 3, 1, 2, 1, 0, 1, 1, 2, 2, 0, 0, 2, 0, 2, 3, 1, 3, 0, 0, 1, 0, 2, 0, 1, 1, 0, 2, 1, 3, 3, 2, 3, 3, 3, 0, 1, 3, 2, 3, 0, 3, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 3, 0, 3, 1, 3, 0, 1, 0, 1, 1, 0, 2, 2, 1, 0, 2, 0, 1, 0, 1, 1, 3, 3, 1, 0, 3, 1, 3]

lst
0    201
1    189
2    200
3    210
Name: count, dtype: int64

In [135]:
df2 = df.set_index('Type 1')
df2

,#,Name,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Types,count,lst
Type 1,,,,,,,,,,,,,,,
Grass,1,Bulbasaur,Poison,94,45,49,49,65,65,45,Test 1,Test 2,Grass&Poison,1,2
Grass,2,Ivysaur,Poison,122,60,62,63,80,80,60,Test 1,Test 2,Grass&Poison,1,2
Grass,3,Venusaur,Poison,162,80,82,83,100,100,80,Test 1,Test 2,Grass&Poison,1,3
Grass,3,VenusaurMega Venusaur,Poison,180,80,100,123,122,120,80,Test 1,Test 2,Grass&Poison,1,3
Fire,4,Charmander,NaN,91,39,52,43,60,50,65,1,True,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Rock,719,Diancie,Fairy,150,50,100,150,100,150,50,Test 1,Test 2,Rock&Fairy,1,1
Rock,719,DiancieMega Diancie,Fairy,210,50,160,110,160,110,110,Test 1,Test 2,Rock&Fairy,1,0
Psychic,720,HoopaHoopa Confined,Ghost,190,80,110,60,150,130,70,Test 1,Test 2,Psychic&Ghost,1,3
Psychic,720,HoopaHoopa Unbound,Dark,240,80,160,60,170,130,80,Test 1,Test 2,Psychic&Dark,1,1
Fire,721,Volcanion,Water,190,80,110,120,130,90,70,Test 1,Test 2,Fire&Water,1,3

# Some lambdas

In [137]:
add = lambda a, b: a + b
print(add(3, 8))

11

In [138]:
def add2(a=4, b=2):
  return a + b
print(add2())

6

In [139]:
add = lambda a: a+5
print(add(5))

10

In [140]:
(lambda a, b: a+b)(3, 5)

8

In [141]:
product = lambda x, y, z = 7: x*y*z
print(product(z=5, x=1, y=1))

5

In [142]:
add = lambda *args: sum(args)
print(add(1, 2, 3, 4, 5))

15

In [143]:
h_o = lambda x, fun: x + fun(x)
h_o(5, lambda x: x*x)

30

In [144]:
print(12%5)

2

In [146]:
(lambda x: (x%2) and 'odd' or 'even')(11)

'odd'

In [147]:
s_str = lambda string: string in 'Python classes'
s_str('Python')

True

In [148]:
nums = [10, 40, 80, 160, 240]
g = list(filter(lambda num: num > 80, nums))

In [151]:
list(filter(lambda num: (num%4) == 0, nums))

[40, 80, 160, 240]

In [149]:
g

[160, 240]

In [150]:
d = list(map(lambda x: x*2, nums))
d

[20, 80, 160, 320, 480]

In [153]:
from functools import reduce
nums= [1,2]
summ = reduce((lambda x, y: x/y), nums)
summ

0.5

In [154]:
def quadract(a, b, c):
  return lambda x: a*x**2 + b*x + c
f = quadract(2, 3, 5)
print(f(1))

10

In [155]:
import pandas as pd

table1 = pd.DataFrame(data = {'col1': [1, 2, 3], 'col2': [4, 5, 6]})
table2 = pd.DataFrame(data = {'col1': [4, 5, 6], 'col2': [7, 8, 9]})
table3 = pd.DataFrame(data = {'col3': [1, 1, 2], 'col4': [4, 4, 6]})
print(table1)
print(table2)
print(table3)

   col1  col2
0     1     4
1     2     5
2     3     6
   col1  col2
0     4     7
1     5     8
2     6     9
   col3  col4
0     1     4
1     1     4
2     2     6

In [156]:
pd.concat([table1, table2])

   col1  col2
0     1     4
1     2     5
2     3     6
0     4     7
1     5     8
2     6     9

In [159]:
print(table1)
print(table2)
pd.merge(table1, table2, on='col2', how='right')

   col1  col2
0     1     4
1     2     5
2     3     6
   col1  col2
0     4     7
1     5     8
2     6     9

   col1_x  col2  col1_y
0     NaN     7       4
1     NaN     8       5
2     NaN     9       6

In [158]:
pd.concat([table1, table3])

   col1  col2  col3  col4
0   1.0   4.0   NaN   NaN
1   2.0   5.0   NaN   NaN
2   3.0   6.0   NaN   NaN
0   NaN   NaN   1.0   4.0
1   NaN   NaN   1.0   4.0
2   NaN   NaN   2.0   6.0

In [160]:
table1 = pd.DataFrame(data = {'col1': [1, 2, 3], 'col2': [4, 5, 6]})
table2 = pd.DataFrame(data = {'col1': [4, 5, 6], 'col2': [4, 5, 9]})
table3 = pd.DataFrame(data = {'col3': [1, 1, 2], 'col4': [4, 4, 6]})
print(table1)
print(table2)
pd.merge(table1, table2, on='col2', how='outer')

   col1  col2
0     1     4
1     2     5
2     3     6
   col1  col2
0     4     4
1     5     5
2     6     9

   col1_x  col2  col1_y
0     1.0     4     4.0
1     2.0     5     5.0
2     3.0     6     NaN
3     NaN     9     6.0

In [161]:
table1 = pd.DataFrame(data = {'col1': [1, 2, 3], 'col2': [4, 5, 6]})
table2 = pd.DataFrame(data = {'col1': [4, 5, 6], 'col2': [4, 5, 9]})
table3 = pd.DataFrame(data = {'col3': [1, 1, 2], 'col4': [6, 8, 9]})
print(table1)
print(table3)
pd.merge(table1, table3, left_on='col2', right_on='col4', how='left')

   col1  col2
0     1     4
1     2     5
2     3     6
   col3  col4
0     1     6
1     1     8
2     2     9

   col1  col2  col3  col4
0     1     4   NaN   NaN
1     2     5   NaN   NaN
2     3     6   1.0   6.0

In [162]:
print(table1)
print(table3)

# col1 col2 col3 col4
# 1, 4, 1, 4
# 1, 4, 1, 4
# 2, 5, 2, 6
# 3, 6, NaN, NaN
pd.merge(table1, table3, left_on='col2', right_on='col4', how='outer')

   col1  col2
0     1     4
1     2     5
2     3     6
   col3  col4
0     1     6
1     1     8
2     2     9

   col1  col2  col3  col4
0   1.0   4.0   NaN   NaN
1   2.0   5.0   NaN   NaN
2   3.0   6.0   1.0   6.0
3   NaN   NaN   1.0   8.0
4   NaN   NaN   2.0   9.0

In [163]:
print(table1)
print(table3)
pd.merge(table1, table3, left_on='col2', right_on='col4', how='inner')

   col1  col2
0     1     4
1     2     5
2     3     6
   col3  col4
0     1     6
1     1     8
2     2     9

   col1  col2  col3  col4
0     3     6     1     6

In [164]:

print(table1)
print(table3)
pd.merge(table1, table3, left_on='col2', right_on='col4', how='right')

   col1  col2
0     1     4
1     2     5
2     3     6
   col3  col4
0     1     6
1     1     8
2     2     9

   col1  col2  col3  col4
0   3.0   6.0     1     6
1   NaN   NaN     1     8
2   NaN   NaN     2     9